# Generated by Django 5.1 on 2024-08-21 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('stock', models.IntegerField(default=1, verbose_name='Stock')),
                ('category', models.CharField(blank=True, choices=[('men-clothing', 'Men Clothing'), ('women-clothing', 'Women Clothing'), ('kids-clothing', 'Kids Clothing'), ('watches', 'Watches'), ('shoes & handbags', 'Shoes & Handbags'), ('books', 'Books'), ('home & kitchen', 'Home & Kitchen'), ('health & personalcares', 'Health & Personalcares'), ('gifts', 'Gifts')], null=True, verbose_name='Category')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='product-image/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
