# Generated by Django 5.1 on 2024-08-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('men-clothing', 'Men Clothing'), ('women-clothing', 'Women Clothing'), ('kids-clothing', 'Kids Clothing'), ('watches', 'Watches'), ('shoes & handbags', 'Shoes & Handbags'), ('books', 'Books'), ('home & kitchen', 'Home & Kitchen'), ('health & personalcares', 'Health & Personalcares'), ('gifts', 'Gifts')], max_length=50, null=True, verbose_name='Category'),
        ),
    ]
